In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import matplotlib
from wordcloud import WordCloud
from pathlib import Path

In [7]:
# Load the data
analyst_df=pd.read_csv('DataAnalyst.csv')
analyst_df

# Preview the data
analyst_df.head(20)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),Weâ€™re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True
5,5,Data Analyst,$37K-$66K (Glassdoor est.),About Cubist\nCubist Systematic Strategies is ...,3.9,Point72\n3.9,"New York, NY","Stamford, CT",1001 to 5000 employees,2014,Company - Private,Investment Banking & Asset Management,Finance,Unknown / Non-Applicable,-1,-1
6,6,Business/Data Analyst (FP&A),$37K-$66K (Glassdoor est.),Two Sigma is a different kind of investment ma...,4.4,Two Sigma\n4.4,"New York, NY","New York, NY",1001 to 5000 employees,2001,Company - Private,Investment Banking & Asset Management,Finance,Unknown / Non-Applicable,-1,-1
7,7,Data Science Analyst,$37K-$66K (Glassdoor est.),Data Science Analyst\n\nJob Details\nLevel\nEx...,3.7,GNY Insurance Companies\n3.7,"New York, NY","New York, NY",201 to 500 employees,1914,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),"Travelers, Chubb, Crum & Forster",True
8,8,Data Analyst,$37K-$66K (Glassdoor est.),The Data Analyst is an integral member of the ...,4.0,DMGT\n4.0,"New York, NY","London, United Kingdom",5001 to 10000 employees,1896,Company - Public,Venture Capital & Private Equity,Finance,$1 to $2 billion (USD),"Thomson Reuters, Hearst, Pearson",-1
9,9,"Data Analyst, Merchant Health",$37K-$66K (Glassdoor est.),About Us\n\nRiskified is the AI platform power...,4.4,Riskified\n4.4,"New York, NY","New York, NY",501 to 1000 employees,2013,Company - Private,Research & Development,Business Services,Unknown / Non-Applicable,"Signifyd, Forter",-1
10,10,Data Analyst,$37K-$66K (Glassdoor est.),NYU Grossman School of Medicine is one of the ...,4.0,NYU Langone Health\n4.0,"New York, NY","New York, NY",10000+ employees,1841,Hospital,Health Care Services & Hospitals,Health Care,$5 to $10 billion (USD),"NewYork-Presbyterian Hospital, Northwell Health",-1
11,11,Data Analyst,$37K-$66K (Glassdoor est.),BulbHead is currently seeking a Data Analyst t...,-1.0,BulbHead,"Fairfield, NJ",-1,1 to 50 employees,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1,-1
12,12,DATA ANALYST,$37K-$66K (Glassdoor est.),Job Summary:\n\nThe Clinical Research Data Ana...,3.7,Montefiore Medical\n3.7,"New York, NY","Bronx, NY",10000+ employees,1884,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
13,13,Senior Data Analyst,$37K-$66K (Glassdoor est.),About Known\n\nKnown is a modern marketing com...,3.0,Known\n3.0,"New York, NY","New York, NY",201 to 500 employees,2004,Company - Private,Advertising & Marketing,Business Services,$100 to $500 million (USD),-1,True
14,14,Investment Advisory Data Analyst,$37K-$66K (Glassdoor est.),Investment Advisory Compliance Opportunity in ...,3.4,Advisor Group\n3.4,"Jersey City, NJ","Phoenix, AZ",1001 to 5000 employees,2016,Company - Private,Brokerage Services,Finance,$1 to $5 million (USD),-1,-1
15,15,Sustainability Data Analyst,$37K-$66K (Glassdoor est.),Job Description\nRole Description\n\nSustainab...,3.6,CodeGreen Solutions\n3.6,"New York, NY","New York, NY",1 to 50 employees,-1,Company - Private,Building & Personnel Services,Business Services,Unknown / Non-Applicable,-1,-1
16,16,Data Analyst,$37K-$66K (Glassdoor est.),Undertone stands alone among AdTech and ad net...,3.8,Undertone\n3.8,"New York, NY","New York, NY",201 to 500 employees,2001,Subsidiary or Business Segment,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"DoubleClick, Specific Media, Collective",True
17,17,Clinical Data Analyst,$37K-$66K (Glassdoor est.),About Us:\n\nNYSTEC is a non-profit technology...,3.8,NYSTEC\n3.8,"New York, NY","Rome, NY",51 to 200 employees,1996,Nonprofit Organization,Consulting,Business Services,$25 to $50 million (USD),"KPMG, Accenture, Deloitte",-1
18,18,DATA PROGRAMMER/ANALYST,$37K-$66K (Glassdoor est.),Company Description\n\nEDUCATION DEVELOPMENT C...,3.9,"Education Development Center, Inc.\n3.9","New York, NY","Waltham, MA",501 to 1000 employees,1958,Nonprofit Organization,Research & Development,Business Services,$100 to $500 million (USD),-1,-1
19,19,Data Analyst,$37K-$66K (Glassdoor est.),"About Us\n\nAt Teachers Pay Teachers (TpT), we...",4.9,Teachers Pay Teachers\n4.9,"New York, NY","New York, NY",51 to 200 employees,2006,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,-1,-1

In [5]:
#Potential questions: what data is correlated with teh highest salaries